config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  authenticated :account do
    root to: 'home#index', as: 'authenticated_root'
  end

  devise_scope :account do
    resources :groups, except: [:edit, :new], controller: 'groups'
    resources :contacts, except: [:index]
    get '/contacts/delete/:id', to: 'contacts#delete', as: 'contacts_get_delete'
    root 'devise/sessions#new'
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups

  def self.setup_account account
    if account.groups.count == 0
      account.groups.create name: 'All'
      account.reload
    end
    account
  end

end

app/models/address.rb
class Address < ActiveRecord::Base

  belongs_to :contact, counter_cache: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  has_many :addresses
  belongs_to :group, counter_cache: true

  validates :name, presence: true
  validates :phones, phone_number: true
  validates :emails, email: true

  def self.search(search_query, group_id, account)
    account = Account.setup_account account
    query = Contact
    if group_id
      query = query.where(group_id: group_id)
    else
      query = query.where(group_id: account.groups.first.id)
    end

    if search_query
      query = query.where(':search_query = ANY(emails) or :search_query = ANY(phones) or name LIKE(:name_query)',
                          {search_query: search_query , name_query: "%#{search_query}%"})
    end
    query.order(:name)
  end

end

app/models/group.rb
class Group < ActiveRecord::Base

  validates :name, presence: true, uniqueness: {scope: :account, case_sensitive: false}

  has_many :contacts
  belongs_to :account, counter_cache: true

  scope :with_account, ->(account) { where(account: account) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < SecuredController

  def show
    @contact = Contact.find_by_id(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    group = Group.find_by_id(contact_params[:group_id])
    @contact = group.contacts.create contact_params
    @contact.save
    if @contact.persisted?
      redirect_to contact_url @contact
    else
      render 'contacts/new'
    end
  end

  def edit
    @contact = Contact.find_by_id(params[:id])
  end

  def update
    @contact = Contact.find_by_id(params[:id])
    @contact.update_attributes contact_params
    if @contact.errors.empty?
      redirect_to contact_url @contact
    else
      render 'contacts/new'
    end
  end

  def destroy
    contact = Contact.find_by_id(params[:id])
    if contact.nil?
      render status: 400
    else
      contact.destroy!
      render json: {}
    end
  end

  def delete
    contact = Contact.find_by_id(params[:id])
    contact.destroy! if contact
    redirect_to root_path
  end

  def contact_params
    params.require(:contact).permit(:name, :group_id, :emails => [], :phones => [])
  end

end

app/controllers/groups_controller.rb
class GroupsController < SecuredController

  respond_to :json

  def index
    respond_with current_account.groups.order(:name)
  end

  def create
    group = current_account.groups.create group_params
    if group.persisted?
      html_content = render_to_string partial: '/partials/group_item', locals: {group: group}, formats: :html
      render json: {group: group, html: html_content}
    else
      response.status = 400
      render partial: '/partials/error_list', object: group.errors, formats: :html
    end
  end

  def update
    group = Group.find_by_id(params[:id])
    if group.nil?
      render status: 400
    else
      group.update_attributes group_params
      if group.errors.empty?
        respond_with nil
      else
        response.status = 400
        render partial: '/partials/error_list', object: group.errors, formats: :html
      end
    end
  end

  def destroy
    group = Group.find_by_id(params[:id])
    if group.nil?
      render status: 400
    else
      if group.contacts.count != 0
        default_group = Group.find_by_name('All')
        Contact.where(group: group).all.each do|contact|
          contact.group = default_group
          contact.save! #not very good to update here.
          default_group.contacts << contact
          default_group.save!
        end
      end
      group.reload.destroy!
      respond_with nil
    end
  end

  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < SecuredController

  def index
    @data = {current_group: nil, contacts: []}
    @data[:contacts] = Contact.search params[:search], params[:group_id], current_account
    @data[:current_group] = Group.find_by_id(params[:group_id])
  end
  
end

app/controllers/secured_controller.rb
class SecuredController < ApplicationController

  before_action :authenticate_account!

end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_error_messages!(resource)
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="alert alert-danger">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/contacts/_form.html.erb
<% unless @contact.errors.empty?%>
    <div class="alert alert-danger">
        <ul>
            <% @contact.errors.full_messages.each do|msg|%>
                <li><%= msg%></li>
            <% end%>
        </ul>
    </div>
<% end %>
<div class="form-group">
    <label class="col-sm-2 control-label">Groups</label>
    <div class="col-sm-10">
        <%= f.collection_select :group_id, current_account.groups.order(:name),:id,:name, {include_blank: false}, {class: 'form-control'} %>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <%= f.text_field :name, {class: 'form-control', placeholder: 'Enter name'}%>
    </div>
</div>
<hr/>
<div class="email-fields">
    <div class="form-group">
        <label class="col-sm-2 control-label">Emails</label>
        <div class="col-sm-10">
            <button class="btn btn-primary btn-add-email-field" type="button">
                <i class="fa fa-plus-circle"></i>&nbsp;Add Email Address
            </button>
        </div>
    </div>
    <% contact.emails.each.with_index do |email, index|%>
        <div class="form-group" id="email<%= index%>">
            <div class="col-sm-offset-2 col-sm-8">
                <input type="text" name="contact[emails][]" class="form-control"
                       placeholder="Enter email address" value="<%= email%>">
            </div>
            <div class="col-sm-2">
                <div class="btn-group" role="group">
                    <button class="btn btn-primary btn-add-email-field"
                            type="button" id="btn-add-email-field<%= index%>">
                        <i class="fa fa-plus-circle"></i>
                    </button>
                    <button class="btn btn-danger btn-remove-email-field" type="button"
                            id="btn-remove-email-field<%= index%>"
                            data-id="email<%= index%>">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </div>
            </div>
        </div>
    <% end%>
</div>
<hr/>
<div class="phone-fields">
    <div class="form-group">
        <label class="col-sm-2 control-label">Phones</label>
        <div class="col-sm-10">
            <button class="btn btn-primary btn-add-phone-field" type="button">
                <i class="fa fa-plus-circle"></i>&nbsp;Add Phone Number
            </button>
        </div>
    </div>
    <% contact.phones.each.with_index do |phone, index|%>
        <div class="form-group" id="phone<%= index%>">
            <div class="col-sm-offset-2 col-sm-8">
                <input type="text" name="contact[phones][]" class="form-control"
                       placeholder="Enter email address" value="<%= phone%>">
            </div>
            <div class="col-sm-2">
                <div class="btn-group" role="group">
                    <button class="btn btn-primary btn-add-email-field"
                            type="button" id="btn-add-phone-field<%= index%>">
                        <i class="fa fa-plus-circle"></i>
                    </button>
                    <button class="btn btn-danger btn-remove-phone-field" type="button"
                            id="btn-remove-phone-field<%= index%>"
                            data-id="phone<%= index%>">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </div>
            </div>
        </div>
    <% end%>
</div>
<hr/>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10 text-right">
        <a href="<%= root_path %>" class="btn btn-default">Cancel</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</div>

app/views/contacts/edit.html.erb
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Edit Contact</h3>
                    </div>
                    <div class="panel-body">
                        <%= form_for @contact, html: {class: 'form-horizontal', id: 'add-contact-form'} do |f| %>
                            <%= render partial:'/contacts/form', locals: {contact: @contact, f: f}%>
                        <% end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/contacts/new.html.erb
<section>

    <div class="container">
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Add Contact</h3>
                    </div>
                    <div class="panel-body">
                        <%= form_for @contact, html: {class: 'form-horizontal', id: 'add-contact-form'} do |f| %>
                            <%= render partial:'/contacts/form', locals: {contact: @contact, f: f}%>
                        <% end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/contacts/show.html.erb
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8">
                <div class="panel panel-default contact-card">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center"><a href="#"><%= @contact.name%></a></h3>
                    </div>
                    <div class="panel-body">
                        <div class="text-center">
                            <img src="http://www.gravatar.com/avatar/<%= Digest::MD5.hexdigest(@contact.emails[0]) unless @contact.emails.empty?%>"
                                 alt="" class="img-thumbnail picture"/>
                        </div>
                    </div>
                    <table class="table table-striped table-responsive table-bordered">
                        <tr>
                            <td class="text-right"><p style="margin-top: 10px;">Email</p></td>
                            <td class="text-left">
                                <% if @contact.emails.empty?%>
                                    <p style="margin-top: 10px;">N/A</p>
                                <% else %>
                                    <ul class="list-group">
                                        <% @contact.emails.each do |email|%>
                                            <li class="list-group-item"><%= email%></li>
                                        <% end%>
                                    </ul>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-right"><p style="margin-top: 10px;">Phone</p></td>
                            <td class="text-left">
                                <% if @contact.phones.empty?%>
                                    <p style="margin-top: 10px;">N/A</p>
                                <% else %>
                                    <ul class="list-group">
                                        <% @contact.phones.each do |phone|%>
                                            <li class="list-group-item"><%= phone%></li>
                                        <% end%>
                                    </ul>
                                <% end %>

                            </td>
                        </tr>
                    </table>
                    <div class="panel-footer">
                        <div class="text-right">
                            <a href="<%= edit_contact_path @contact%>" class="btn btn-info btn-sm"
                               data-toggle="tooltip"
                               data-placement="top"
                               title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="<%= contacts_get_delete_path @contact%>" class="btn btn-danger btn-sm btn-delete-contact"
                               data-toggle="tooltip"
                               data-placement="top"
                               data-id="<%= @contact.id%>"
                               title="Delete"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $('.btn-delete-contact').confirm({
        text: "Really want to delete?",
        title: "Confirmation required",
        confirm: function(button) {
            var contactId = button.data('id');
            location.href = '/contacts/delete/' + contactId
        },
        cancel: function(button) {},
        confirmButton: "Delete",
        cancelButton: "Cancel",
        post: false,
        confirmButtonClass: "btn-danger",
        cancelButtonClass: "btn-default",
        dialogClass: "modal-dialog modal-sm" // Bootstrap classes for large modal
    });
</script>

app/views/home/index.html.erb
<% groups = current_account.groups.order(:name)%>
<% current_group = @data[:current_group]%>
<% contacts = @data[:contacts]%>
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3">
                <%= render partial: 'partials/groups', object: groups, locals: {current_group: current_group} %>
            </div>
            <div class="col-lg-9">
                <div class="pull-left">
                    <h3 class="panel-title" id="contact-list-title" style="margin-top: 7px;">
                        <% if current_group %>
                            Contacts in <%= current_group.name %>
                        <% elsif !groups.empty? %>
                            Contacts in <%= groups.first.name %>
                        <% else %>
                            All Contacts
                        <% end %>
                    </h3>
                </div>
                <div class="pull-right">
                    <a href="<%= new_contact_path%>" class="btn btn-default btn-sm">
                        <i class="fa fa-plus-circle"></i>&nbsp;Add Contact
                    </a>
                </div>
                <div class="clearfix"></div>
                <hr/>
                <div class="row">
                    <div class="col-lg-12">
                        <form method="get">
                            <div class="form-group">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="search" value="<%= params['search'] %>"
                                           placeholder="Type email, name or phone to filter ..."/>
                                    <% if params['group_id'] %>
                                        <input type="hidden" name="group_id" value="<%= params['group_id'] %>"/>
                                    <% end %>
                                    <div class="input-group-btn">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                                </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <% contacts.each do |contact|%>
                        <div class="col-lg-4">
                            <%= render partial: 'partials/contact_card', object: contact %>
                        </div>
                    <% end%>
                </div>
            </div>

        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Address Book</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'partials/nav'%>

<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-offset-4 col-lg-4">
                <% if notice %>
                    <div class="alert alert-info alert-dismissible text-center">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <%= notice %>
                    </div>
                <% end %>
                <% if alert %>
                    <div class="alert alert-danger alert-dismissible text-center">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <%= alert %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>
<%= yield %>

</body>
</html>

app/views/partials/_add_group.html.erb
<!-- Modal -->
<div class="modal fade" id="<%= (edit)?'edit':'add'%>-group-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <form id="<%= (edit)?'edit':'add' %>-group-form">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title"><%= (edit)?'Edit':'Add'%> Group</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" id="<%= (edit)?'edit':'add'%>-group-form-errors" style="display: none;"></div>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="<%= (edit)?'edit':'add'%>-group-input-name" name="group[name]" placeholder="Enter Group Name"
                               required autofocus="true"/>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary"><%= (edit)?'Edit':'Add'%></button>
                </div>
            </div>
        </form>
    </div>
</div>

app/views/partials/_contact_card.html.erb
<div class="panel panel-default contact-card">
    <div class="panel-heading">
        <h3 class="panel-title text-center"><a href="#"><%= contact_card.name%></a></h3>
    </div>
    <div class="panel-body">
        <div class="text-center">
            <img src="http://www.gravatar.com/avatar/<%= Digest::MD5.hexdigest(contact_card.emails[0]) unless contact_card.emails.empty?%>" alt="" class="img-thumbnail picture"/>
        </div>
    </div>
    <table class="table table-striped table-responsive table-bordered">
        <tr>
            <td class="text-right">Email</td>
            <td class="text-left">
                <% if contact_card.emails.empty?%>
                    N/A
                <% else %>
                    <%= contact_card.emails.first%>
                <% end%>
            </td>
        </tr>
        <tr>
            <td class="text-right">Phone</td>
            <td class="text-left">
                <% if contact_card.phones.empty?%>
                    N/A
                <% else %>
                    <%= contact_card.phones.first%>
                <% end%>
            </td>
        </tr>
    </table>
    <div class="panel-footer">
        <div class="text-right">
            <a href="<%= contact_path contact_card%>" class="btn btn-primary btn-sm"
               data-toggle="tooltip"
               data-placement="top"
               title="View details"><i class="fa fa-info-circle"></i></a>
            <a href="<%= edit_contact_path contact_card%>" class="btn btn-info btn-sm"
               data-toggle="tooltip"
               data-placement="top"
               title="Edit"><i class="fa fa-edit"></i></a>
            <a href="#" class="btn btn-danger btn-sm btn-delete-contact"
               data-toggle="tooltip"
               data-placement="top"
               data-id="<%= contact_card.id%>"
               title="Delete"><i class="fa fa-trash-o"></i></a>
        </div>
    </div>
</div>

<script>
    $('.btn-delete-contact').confirm({
        text: "Really want to delete?",
        title: "Confirmation required",
        confirm: function(button) {
            var contactId = button.data('id');
            location.href = '/contacts/delete/' + contactId
        },
        cancel: function(button) {},
        confirmButton: "Delete",
        cancelButton: "Cancel",
        post: false,
        confirmButtonClass: "btn-danger",
        cancelButtonClass: "btn-default",
        dialogClass: "modal-dialog modal-sm" // Bootstrap classes for large modal
    });
</script>

app/views/partials/_error_list.html.erb
<ul class="error-list">
    <% error_list.full_messages.each do |error| %>
        <li><%= error%></li>
    <% end%>
</ul>

app/views/partials/_group_item.html.erb
<% current_group ||= nil%>
<% i ||= -1%>
<li class="list-group-item <%= 'active' if (current_group.nil? && i == 0) || current_group == group %>">
    <div class="pull-left" style="padding-top: 5px;">
        <a href="<%= root_path(group_id: group.id) %>" id="<%= "group-name#{group.id}"%>"><%= group.name %></a>
    </div>
    <div class="pull-right">
        <% unless group.name == 'All' %>
            <button type="button" class="btn btn-default btn-sm group-edit-btn" id="<%= "group-edit-btn#{group.id}"%>"
                    data-id="<%= group.id%>" data-name="<%= group.name%>">
                <i class="fa fa-edit"></i>
            </button>
            <button type="button" class="btn btn-danger btn-sm group-delete-btn" id="<%= "group-delete-btn#{group.id}"%>"
                    data-id="<%= group.id%>" data-name="<%= group.name%>">
                <i class="fa fa-trash-o"></i>
            </button>
        <% end%>
    </div>
    <div class="clearfix"></div>
</li>

app/views/partials/_groups.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="pull-left">
            <h3 class="panel-title" style="margin-top: 5px;">Groups</h3>
        </div>
        <div class="pull-right">
            <button type="button" class="btn btn-default btn-sm"
                    data-toggle="modal" data-target="#add-group-modal">
                <i class="fa fa-plus-circle"></i>&nbsp;Add Group
            </button>
        </div>
        <div class="clearfix"></div>
    </div>
    <ul class="list-group groups">
        <% groups.each.with_index do |group, i| %>
            <%= render partial: 'partials/group_item', locals: {group: group, current_group: current_group, i: i} %>
        <% end %>
    </ul>
</div>

<%= render partial: 'partials/add_group', locals:{edit: false} %>
<%= render partial: 'partials/add_group', locals:{edit: true} %>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path%>">Simple Address Book</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if account_signed_in? %>
                    <li><a href="<%= destroy_account_session_path %>"><i class="fa fa-sign-out"></i>&nbsp;Logout</a></li>
                <% else %>
                    <li><a href="<%= new_account_session_path %>"><i class="fa fa-sign-in"></i>&nbsp;Sign in</a></li>
                    <li><a href="<%= new_account_registration_path %>">Register</a></li>
                <% end %>

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>